import { Metadata } from "next"

import "./globals.css"
import Navbar from "../components/navbar"
import Header from "@/components/header"


export const metadata: Metadata = {
  title: "Diegoxes Portfolio",
  description: "Generated by Diego Mendoza",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
      <html>
        <body>
          <Navbar/>   
          <Header/>
          {children}
        </body>
      </html>
    
  )
}
